create shopVehicleMethod
develhope/Java23-Team1-Dealer pull request #36
Opened 2024-05-31 08:24 UTC by Sijia18

2024-05-31 13:10 UTC, emmathebear requested changes

2024-05-31 13:10 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +    public List<Vehicle> readPurchasedVehiclesByUserId(Long userId) {
scriverei find non read

2024-05-31 13:10 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +    public boolean shopVehicle(Vehicle vehicle, VehicleState isPurchasable) {
MA cosa fa questo metodo, per comprare un veicolo dovrebbe essere creato un ordine

2024-06-02 10:35 UTC, hatefulTtamer requested changes

2024-06-02 10:35 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
>          return ResponseEntity.ok(vehicleAdded);
visto che hai utilizzato ResponseEntity si potrebbero valutare anche i casi in cui lo status non è 200 ma un error, e quindi valutare sia la creazione riuscita che quella non riuscita.

2024-06-02 10:35 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +                return ResponseEntity.ok("Vehicle has been successfully purchased!");
Non capisco se questo metodo comprende l'effettivo acquisto di un veicolo o se è solo un setter per l'enum. Purchasable indica "acquistabile", non acquistato, quindi questa richiesta post dovrebbe essere in realtà put, ed in secondo luogo andrebbe gestita utilizzando un Path Variable con l'id in cui andiamo effettivamente a prendere un veicolo già inserito in database ed impostarlo come acquistato (ripeto, ammesso che lo scopo sia quello e che non sia semplicemente un riferimento "acquistabile", e quindi nel listino).

2024-06-02 10:35 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +                return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("This user " + userId + " has not yet purchased vehicles with us.");
Meglio utilizzare un 204 no content, la richiesta va effettivamente a buon fine anche se la lista è vuota

2024-06-02 10:35 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +            System.out.println("Vehicle has been successfully purchased!");
Non c'è bisogno di aggiungere System.out, meglio evitare

2024-06-03 11:57 UTC, hatefulTtamer requested changes

2024-06-03 11:57 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +            return ResponseEntity.status(HttpStatus.NO_CONTENT).body("Order not found for user " + userId + ": " + e.getMessage());
Questa ResponseEntity dovrebbe sostituire quella di riga 50, dovresti invertirle

2024-06-03 11:57 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +            return ResponseEntity.ok(vehicleAdded);
Potresti sostituire questo status ok con un 201 "created"

2024-06-03 11:57 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +    @PostMapping("/shop")
In questa post manca effettivamente l'id dell'utente effettuante la richiesta, inoltre non sono sicuro che vada effettuata una post ma per ora va bene così

2024-06-03 13:25 UTC, emmathebear requested changes
Ci sono troppi argomenti diversi in quest'unica pull request. 
- Dividere in una pull almeno per categoria (in questo caso Order e Vehicle), se un metodo è lungo una per metodo.
- Non inserire logica nel controller.
- Gestire le eccezioni con il Global Exception handler.

2024-06-03 13:25 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +    public ResponseEntity<String> shopVehicle(@RequestBody Vehicle vehicle, @RequestParam VehicleState isPurchasable) {
Non mi è chiaro quale sia la logica di questo metodo

2024-06-03 13:25 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +    public ResponseEntity<String> findPurchasedVehiclesByUserId(@PathVariable Long userId, Order order) {
Perché prende un ordine in ingresso? Non dovrebbe andare a vedersi tutti gli ordini fatti da quell'utente e restituirci una lista dei veicoli?

2024-06-03 13:25 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +    private OrderRepository orderRepository;
Manca l'annotazione @Autowired

2024-06-03 13:25 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +    public boolean shopVehicle(Vehicle vehicle, VehicleState isPurchasable){
Qui dovrebbe prendere un id più che tutto un veicolo, ci sono tutti i dati per creare un nuovo ordine?
Andrebbe nell'order service

2024-06-03 13:25 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +        if (vehicle == null || isPurchasable == null) {
Passando l'id questo diventa superfluo

2024-06-03 13:25 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +    public List<Vehicle> findPurchasedVehiclesByUserId(Long userId, Order order) {
Come sopra, poi è un metodo relativo non ai veichles ma agli ordini quindi andrebbe nei service degli ordini.

2024-06-03 13:32 UTC, emmathebear requested changes

2024-06-03 13:32 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
Tutte le eccezioni vanno gestite con il Global exceptionHandler

2024-06-10 11:17 UTC, closed without merging