Demo fix
develhope/Java23-Team1-Dealer pull request #52
Opened 2024-06-07 13:33 UTC by emmathebear

2024-06-07 13:38 UTC, fab-bob approved these changes

2024-06-07 14:10 UTC, hatefulTtamer requested changes

2024-06-07 14:35 UTC, emmathebear commented on src/main/resources/application-h2.properties
>  # Configurazione JPA/Hibernate
ricordami cosa dovrei fare?

2024-06-10 10:32 UTC, hatefulTtamer approved these changes

2024-06-10 10:32 UTC, merged