create findMostExpensiveSoldedVehicle, need to add it in Service and …
develhope/Java23-Team1-Dealer pull request #59
Opened 2024-06-10 23:58 UTC by hatefulTtamer

…test it

2024-06-11 12:36 UTC, Sijia18 commented on src/main/java/com/develhope/spring/vehicles/controller/VehicleController.java
> +    @GetMapping("/mostExpensiveSoldedVehicle")
dato che il filtro fa riferimento a soldedVehicle, mi chiedo se si debba prendere in considerazione Vehicle o Order(che interpretiamo infatti come veicoli venduti)

2024-06-11 20:01 UTC, emmathebear approved these changes

2024-06-11 21:08 UTC, emmathebear requested changes

2024-06-11 21:08 UTC, emmathebear commented on src/main/java/com/develhope/spring/vehicles/service/VehicleService.java
> +            if (vehicle.isPurchasable() && vehicle.getPrice() > mostExpensiveSoldedVehicle.getPrice()) {
Non dovrebbe controllare se è sold come stato?

2024-06-11 21:08 UTC, emmathebear commented on src/main/resources/application.yml
questo file non dovrebbero essere postato, aggiungi a .gitignore

2024-06-12 19:31 UTC, emmathebear approved these changes

2024-06-14 09:17 UTC, Sijia18 approved these changes

2024-06-14 09:28 UTC, merged