Aggiunti alcuni parametri a Order e DTO in uscita
develhope/Java23-Team1-Dealer pull request #60
Opened 2024-06-11 19:26 UTC by emmathebear

2024-06-11 19:35 UTC, hatefulTtamer requested changes

2024-06-11 19:35 UTC, hatefulTtamer commented on src/main/java/com/develhope/spring/order/dto/ResponseOrderDto.java
> +public class ResponseOrderDto {
Credo sia meglio chiamare la classe OrderResponseDTO

2024-06-11 19:35 UTC, hatefulTtamer commented on src/test/java/com/develhope/spring/OrderTests.java
>  public class OrderTests {
Anche qui chiamiamo le classi al singolare

2024-06-11 19:35 UTC, hatefulTtamer commented on src/test/java/com/develhope/spring/TestOrderMapper.java
> +public class TestOrderMapper {
So che sono un rompicoglioni ma credo sia meglio OrderMapperTest

2024-06-12 07:15 UTC, SIlvioVutea approved these changes

2024-06-12 07:15 UTC, merged