Rent component creator
develhope/Java23-Team1-Dealer pull request #64
Opened 2024-06-12 15:31 UTC by hatefulTtamer

2024-06-12 15:58 UTC, fab-bob approved these changes

2024-06-12 16:00 UTC, fab-bob approved these changes
ho notato che ci sono delle cose che erano state modificate già nell'altro task, io faccio l'approve ma spero che poi nel merge non ci siano conflitti

2024-06-14 07:06 UTC, emmathebear requested changes
I metodi dovrebbero ritornare un dto 
Mancano i test, ma essendo tanta roba forse li includerei in un altra pull...

2024-06-16 16:53 UTC, emmathebear approved these changes

2024-06-16 17:10 UTC, merged